server.port=8082
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auction_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

wallet.service.url=${WALLET_SERVICE_URL:http://localhost:8083}
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
